version: '3'

services:
  client:
    image: alextanhongpin/node-grpc-client:latest
    ports:
      - 4000:8080
    environment:
      - GRPC_HOST=linkerd:4142

  server:
    image: alextanhongpin/node-grpc:latest
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongodb://docker.for.mac.localhost:27017/demo
      - PORT=8080
  
  linkerd:
    image: buoyantio/linkerd:latest
    container_name: linkerd
    ports:
      - 4142:4142
      - 4141:4141
      - 9990:9990
    volumes:
      - ./config:/io.buoyant/linkerd/config:ro
    command:
      - /io.buoyant/linkerd/config/linkerd.yml

  namerd:
    image: buoyantio/namerd:latest
    container_name: namerd
    ports: 
      - 4100:4100 
      - 4180:4180
      - 9991:9991
    volumes: 
      - ./config:/io.buoyant/linkerd/config:ro
    command: /io.buoyant/linkerd/config/namerd.yml