routers:
- protocol: http
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd/4100
  servers:
  - port: 4141
    ip: 0.0.0.0

- protocol: h2
  experimental: true
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd/4100
  servers:
  - port: 4142
    ip: 0.0.0.0
  dstPrefix: /grpc
  identifier:
    kind: io.l5d.header.path
