/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf')
var goog = jspb
var global = Function('return this')()

goog.exportSymbol('proto.transaction.TransactionRequest', null, global)
goog.exportSymbol('proto.transaction.TransactionResponse', null, global)
goog.exportSymbol('proto.transaction.TransactionResponse.Type', null, global)

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.TransactionRequest = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.transaction.TransactionRequest, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.transaction.TransactionRequest.displayName = 'proto.transaction.TransactionRequest'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
  proto.transaction.TransactionRequest.prototype.toObject = function (opt_includeInstance) {
    return proto.transaction.TransactionRequest.toObject(opt_includeInstance, this)
  }

/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.TransactionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
  proto.transaction.TransactionRequest.toObject = function (includeInstance, msg) {
    var f, obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, '')
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.TransactionRequest}
 */
proto.transaction.TransactionRequest.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.transaction.TransactionRequest()
  return proto.transaction.TransactionRequest.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.TransactionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.TransactionRequest}
 */
proto.transaction.TransactionRequest.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setId(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.TransactionRequest.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.transaction.TransactionRequest.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.TransactionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TransactionRequest.serializeBinaryToWriter = function (message, writer) {
  var f
  f = message.getId()
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    )
  }
}

/**
 * optional string id = 1;
 * @return {string}
 */
proto.transaction.TransactionRequest.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/** @param {string} value */
proto.transaction.TransactionRequest.prototype.setId = function (value) {
  jspb.Message.setField(this, 1, value)
}

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.transaction.TransactionResponse = function (opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null)
}
goog.inherits(proto.transaction.TransactionResponse, jspb.Message)
if (goog.DEBUG && !COMPILED) {
  proto.transaction.TransactionResponse.displayName = 'proto.transaction.TransactionResponse'
}

if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
  proto.transaction.TransactionResponse.prototype.toObject = function (opt_includeInstance) {
    return proto.transaction.TransactionResponse.toObject(opt_includeInstance, this)
  }

/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.transaction.TransactionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
  proto.transaction.TransactionResponse.toObject = function (includeInstance, msg) {
    var f, obj = {
        id: jspb.Message.getFieldWithDefault(msg, 1, ''),
        createdAt: jspb.Message.getFieldWithDefault(msg, 2, 0),
        updatedAt: jspb.Message.getFieldWithDefault(msg, 3, 0),
        name: jspb.Message.getFieldWithDefault(msg, 4, ''),
        amount: +jspb.Message.getFieldWithDefault(msg, 5, 0.0),
        type: jspb.Message.getFieldWithDefault(msg, 6, 0)
      }

    if (includeInstance) {
      obj.$jspbMessageInstance = msg
    }
    return obj
  }
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.transaction.TransactionResponse}
 */
proto.transaction.TransactionResponse.deserializeBinary = function (bytes) {
  var reader = new jspb.BinaryReader(bytes)
  var msg = new proto.transaction.TransactionResponse()
  return proto.transaction.TransactionResponse.deserializeBinaryFromReader(msg, reader)
}

/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.transaction.TransactionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.transaction.TransactionResponse}
 */
proto.transaction.TransactionResponse.deserializeBinaryFromReader = function (msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break
    }
    var field = reader.getFieldNumber()
    switch (field) {
      case 1:
        var value = /** @type {string} */ (reader.readString())
        msg.setId(value)
        break
      case 2:
        var value = /** @type {number} */ (reader.readInt64())
        msg.setCreatedAt(value)
        break
      case 3:
        var value = /** @type {number} */ (reader.readInt64())
        msg.setUpdatedAt(value)
        break
      case 4:
        var value = /** @type {string} */ (reader.readString())
        msg.setName(value)
        break
      case 5:
        var value = /** @type {number} */ (reader.readFloat())
        msg.setAmount(value)
        break
      case 6:
        var value = /** @type {!proto.transaction.TransactionResponse.Type} */ (reader.readEnum())
        msg.setType(value)
        break
      default:
        reader.skipField()
        break
    }
  }
  return msg
}

/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.transaction.TransactionResponse.prototype.serializeBinary = function () {
  var writer = new jspb.BinaryWriter()
  proto.transaction.TransactionResponse.serializeBinaryToWriter(this, writer)
  return writer.getResultBuffer()
}

/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.transaction.TransactionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.transaction.TransactionResponse.serializeBinaryToWriter = function (message, writer) {
  var f
  f = message.getId()
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    )
  }
  f = message.getCreatedAt()
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    )
  }
  f = message.getUpdatedAt()
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    )
  }
  f = message.getName()
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    )
  }
  f = message.getAmount()
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    )
  }
  f = message.getType()
  if (f !== 0.0) {
    writer.writeEnum(
      6,
      f
    )
  }
}

/**
 * @enum {number}
 */
proto.transaction.TransactionResponse.Type = {
  INCOME: 0,
  EXPENSE: 1
}

/**
 * optional string id = 1;
 * @return {string}
 */
proto.transaction.TransactionResponse.prototype.getId = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ''))
}

/** @param {string} value */
proto.transaction.TransactionResponse.prototype.setId = function (value) {
  jspb.Message.setField(this, 1, value)
}

/**
 * optional int64 created_at = 2;
 * @return {number}
 */
proto.transaction.TransactionResponse.prototype.getCreatedAt = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0))
}

/** @param {number} value */
proto.transaction.TransactionResponse.prototype.setCreatedAt = function (value) {
  jspb.Message.setField(this, 2, value)
}

/**
 * optional int64 updated_at = 3;
 * @return {number}
 */
proto.transaction.TransactionResponse.prototype.getUpdatedAt = function () {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0))
}

/** @param {number} value */
proto.transaction.TransactionResponse.prototype.setUpdatedAt = function (value) {
  jspb.Message.setField(this, 3, value)
}

/**
 * optional string name = 4;
 * @return {string}
 */
proto.transaction.TransactionResponse.prototype.getName = function () {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ''))
}

/** @param {string} value */
proto.transaction.TransactionResponse.prototype.setName = function (value) {
  jspb.Message.setField(this, 4, value)
}

/**
 * optional float amount = 5;
 * @return {number}
 */
proto.transaction.TransactionResponse.prototype.getAmount = function () {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0))
}

/** @param {number} value */
proto.transaction.TransactionResponse.prototype.setAmount = function (value) {
  jspb.Message.setField(this, 5, value)
}

/**
 * optional Type type = 6;
 * @return {!proto.transaction.TransactionResponse.Type}
 */
proto.transaction.TransactionResponse.prototype.getType = function () {
  return /** @type {!proto.transaction.TransactionResponse.Type} */ (jspb.Message.getFieldWithDefault(this, 6, 0))
}

/** @param {!proto.transaction.TransactionResponse.Type} value */
proto.transaction.TransactionResponse.prototype.setType = function (value) {
  jspb.Message.setField(this, 6, value)
}

goog.object.extend(exports, proto.transaction)
